### PR TITLE
Append a function that automatically adds other incorrect options.

### PR DESCRIPTION
**Pull request by wotchin**
This function was implemented by NLP(Natural Language Processing) module.
This can greatly reduce labor costs and enjoy the benefits of artificial intelligence(AI).

### CODE REVIEW

**Comment by mtancoigne** [comment]
Hi !
Thanks for your PR, i'll test it as soon as possible :)

**Comment by wotchin** [comment]
Thank you.
And by the way,there is a few syntax errors from json file in the folder named 'todo',such as losing '['  or   ']' ,and  appending extra ',' in the end.
So before your test,you could fix the files or the program would product parsing errors.
:)

**Comment by wotchin** [comment]
Ok,see.I will try.

**Comment by wotchin** [comment]
Hello,I have done.

**Comment by mtancoigne** [comment]
I'm looking at it today. By the way, i'm searching for people interested into doing something useful with those data: a website to submit and validate the questions and answers. Are you interested to jump in ? There is still no language or tools defined, so [the discussion is open](https://github.com/el-cms/Open-trivia-database/issues/5)...

**Comment by mtancoigne** [comment]
I tested your script and I got some issues with it, so i'll merge the PR in a `feature/nlp` branch so we can work on it and adapt it before merging in the master branch.

**Pull request merged**
